on:
  push:
    branches:
      - main
      - "feature/**"
      - "bugfix/**"

  pull_request:
    branches:
      - main

jobs:
  prep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build lambda package
        run: |
          cd lambda/ingest/
          pip install -r requirements.txt --target .
          zip -r ../lambda.zip ../ingest/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-pkg
          path: lambda/lambda.zip